package com.songnotes.core.domain

/**
 * Ported from the desktop web app's `src/utils/chords.js`
 * (`normalizeChordName`) — Phase 5 of the plan ("Domain logic port"),
 * whose Done criterion is exactly what `ChordsGoldenFixtureTest` in this
 * module's `src/test` checks: running the same chord strings through both
 * this Kotlin function and the real JS one produces byte-identical
 * output. The fixtures that test reads from (this module's `src/test/resources/spec`
 * directory) were generated by running the actual JS implementation over
 * a broad set of inputs, not hand-predicted — see the desktop `SongNotes`
 * repo's `src/test/generate-golden-fixtures.test.js`.
 *
 * This is a faithful line-by-line port, not a reimplementation from a
 * description — the ordering of the `.replace()` chain in the JS version
 * matters (e.g. the `maj#7`/`maj7` rules must run before the bare `maj`
 * rule, which would otherwise strip `maj` first and leave a meaningless
 * `#7`), so the Kotlin version preserves that exact ordering.
 *
 * [CHORD_DB_KEYS] is intentionally just the **key set** ported here, not
 * the full voicing/fret data (`frets`/`baseFret`/`barre`) — nothing in
 * this phase's scope (chord-name normalization and transposition) needs
 * the actual fretboard shapes; those belong to chord-diagram rendering,
 * which is Phase 8 ("Editor UI") territory.
 */

private val ENHARMONIC: Map<String, String> = mapOf(
    "Gb" to "F#", "Gbm" to "F#m", "Gb7" to "F#7",
    "Cb" to "B", "Cbm" to "Bm",
    "Fb" to "E", "Fbm" to "Em",
    "A#m" to "Bbm",
    "Ebm" to "D#m",
)

/**
 * Normalize a raw user-typed chord name to a canonical key in
 * [CHORD_DB_KEYS]. Returns the normalized name (even if not a recognized
 * chord) — mirrors the JS version's contract exactly, including that the
 * root letter is uppercased unconditionally without validating it's
 * actually A–G.
 */
fun normalizeChordName(raw: String?): String {
    if (raw.isNullOrBlank()) return ""
    val s = raw.trim()

    // Root note.
    val root = s[0].uppercaseChar()
    var rest = s.substring(1)

    // Accidental right after root.
    var acc = ""
    if (rest.isNotEmpty() && rest[0] == '#') {
        acc = "#"
        rest = rest.substring(1)
    } else if (rest.isNotEmpty() && rest[0] == 'b' &&
        !Regex("^[0-9]").containsMatchIn(rest.substring(1))
    ) {
        // treat 'b' as flat only if the next char is not a digit (e.g. "Db" not "D7")
        acc = "b"
        rest = rest.substring(1)
    }

    // Normalize quality suffixes — same order as the JS .replace() chain;
    // order matters (see the maj#7/maj7-before-bare-maj comment above).
    rest = rest.replace(Regex("^-"), "m")
        .replace(Regex("^\\+"), "aug")
        .replace(Regex("^°"), "dim")
        .replace(Regex("^minor\\b", RegexOption.IGNORE_CASE), "m")
        .replace(Regex("^min\\b", RegexOption.IGNORE_CASE), "m")
        .replace(Regex("^maj\\s*#7\\b", RegexOption.IGNORE_CASE), "maj7")
        .replace(Regex("^maj\\s*7\\b", RegexOption.IGNORE_CASE), "maj7")
        .replace(Regex("^maj\\s*9\\b", RegexOption.IGNORE_CASE), "maj9")
        .replace(Regex("^maj\\b", RegexOption.IGNORE_CASE), "")
        .replace(Regex("^M\\b"), "")
        .replace(Regex("^add9\\b", RegexOption.IGNORE_CASE), "add9")
        .replace(Regex("^add11\\b", RegexOption.IGNORE_CASE), "add11")
        .replace(Regex("^sus2\\b", RegexOption.IGNORE_CASE), "sus2")
        .replace(Regex("^sus4\\b", RegexOption.IGNORE_CASE), "sus4")
        .replace(Regex("^sus\\b", RegexOption.IGNORE_CASE), "sus4")
        // strip slash bass note
        .replace(Regex("/[A-G][b#]?\\s*$"), "")
        .trim()

    val name = root + acc + rest
    return ENHARMONIC[name] ?: name
}

/** Just the recognized chord names — see this file's own doc comment for why no voicing data. */
val CHORD_DB_KEYS: Set<String> = setOf(
    "C", "D", "E", "F", "G", "A", "B", "Bb", "Eb", "Ab", "Db", "F#", "Gb", "C#", "G#", "A#", "D#",
    "Am", "Bm", "Cm", "Dm", "Em", "Fm", "Gm", "Bbm", "F#m", "Gbm", "C#m", "Dbm", "G#m", "Abm", "D#m",
    "C7", "D7", "E7", "F7", "G7", "A7", "B7", "Bb7",
    "Cmaj7", "Dmaj7", "Emaj7", "Fmaj7", "Gmaj7", "Amaj7",
    "Am7", "Bm7", "Cm7", "Dm7", "Em7", "Fm7", "Gm7",
    "Asus2", "Asus4", "Dsus2", "Dsus4", "Esus4", "Gsus4",
    "Cadd9", "Gadd9", "Dadd9",
    "Bdim", "Adim", "Edim",
    "C6", "D6", "G6", "A6",
    "Caug", "Cdim7",
    "A5", "E5", "G5", "D5",
)

/**
 * One token of a chord-track line — ported from `tokenizeChordLine`'s
 * per-token object shape in the JS source. [chordName] is null only for
 * whitespace tokens (the JS version simply omits the key there); for
 * every other token it's always set, falling back to [text] itself if
 * [normalizeChordName] produced an empty string.
 */
data class ChordToken(
    val text: String,
    val isChord: Boolean,
    val looksLikeChord: Boolean,
    val isWhitespace: Boolean,
    val chordName: String?,
)

/**
 * Splits a chord-track string into whitespace-run and non-whitespace
 * tokens, classifying each non-whitespace token against [CHORD_DB_KEYS]
 * (plus [customChords], if given — a song's own user-entered voicings,
 * keyed by normalized chord name, taking priority the same way
 * [lookupChord]-equivalent logic would upstream; nothing calls this with
 * a non-null value yet, ported for shape-fidelity ahead of the editor
 * phase that will).
 *
 * Ported by hand-walking `\s+` matches rather than translating
 * `text.split(/(\s+)/)` literally — Kotlin's `String.split` doesn't have
 * an equivalent to JS's capturing-group split (which keeps the
 * delimiters in the result array); this achieves the same effect
 * (whitespace runs become their own tokens, interspersed with the
 * non-whitespace parts between them) without ever producing the
 * empty-string artifacts the JS version's `if (!part) continue` exists
 * to skip.
 */
fun tokenizeChordLine(text: String?, customChords: Map<String, Any?>? = null): List<ChordToken> {
    if (text.isNullOrEmpty()) return emptyList()
    val tokens = mutableListOf<ChordToken>()
    var lastEnd = 0
    for (match in Regex("\\s+").findAll(text)) {
        if (match.range.first > lastEnd) {
            tokens.add(nonWhitespaceChordToken(text.substring(lastEnd, match.range.first), customChords))
        }
        tokens.add(ChordToken(text = match.value, isChord = false, looksLikeChord = false, isWhitespace = true, chordName = null))
        lastEnd = match.range.last + 1
    }
    if (lastEnd < text.length) {
        tokens.add(nonWhitespaceChordToken(text.substring(lastEnd), customChords))
    }
    return tokens
}

private fun nonWhitespaceChordToken(part: String, customChords: Map<String, Any?>?): ChordToken {
    val chordName = normalizeChordName(part)
    val inDb = chordName in CHORD_DB_KEYS || (customChords?.get(chordName) != null)
    return ChordToken(
        text = part,
        isChord = inDb,
        looksLikeChord = Regex("^[A-G][#b]?").containsMatchIn(part),
        isWhitespace = false,
        chordName = chordName.ifEmpty { part },
    )
}

/**
 * Formats a frets array (as stored on a chord voicing) into the compact
 * space-separated text a user can edit, e.g. `[-1,3,2,0,1,0]` -> `"x 3 2 0 1 0"`.
 */
fun formatFretsForInput(frets: List<Int>): String = frets.joinToString(" ") { if (it == -1) "x" else it.toString() }

/** Parsed result of [parseFretsInput] — mirrors the JS version's `{frets, baseFret}` shape. */
data class FretsInput(val frets: List<Int>, val baseFret: Int)

/**
 * Parses a user-typed "x 3 2 0 1 0"-style string (low-E to high-E, 'x' for
 * muted) into a voicing, or null if it isn't exactly 6 valid values.
 * `baseFret` is derived automatically: 1 if the whole shape fits in the
 * first 4 frets (the common case), otherwise the lowest fretted position —
 * same convention every hand-written `CHORD_DB` entry in the JS source
 * follows.
 *
 * One deliberate divergence from a strict byte-for-byte port:
 * `p.toIntOrNull() ?: return null` instead of a direct `p.toInt()` — JS's
 * `Number(p)` never throws (an absurdly long digit string just becomes a
 * huge-but-valid number, which the following `n > 24` check then rejects
 * anyway), but Kotlin's `String.toInt()` throws `NumberFormatException` on
 * overflow. Both end up returning null for that input either way, so this
 * doesn't change behavior — it just reaches the same "reject" outcome
 * without a crash risk Kotlin's typed parsing would otherwise introduce
 * that the JS source never had.
 */
fun parseFretsInput(raw: String?): FretsInput? {
    if (raw.isNullOrEmpty()) return null
    val parts = raw.trim().split(Regex("\\s+"))
    if (parts.size != 6) return null
    val frets = mutableListOf<Int>()
    for (p in parts) {
        if (Regex("^x$", RegexOption.IGNORE_CASE).matches(p)) {
            frets.add(-1)
            continue
        }
        if (!Regex("^\\d+$").matches(p)) return null
        val n = p.toIntOrNull() ?: return null
        if (n > 24) return null
        frets.add(n)
    }
    val played = frets.filter { it > 0 }
    val baseFret = if (played.isEmpty() || played.max() <= 4) 1 else played.min()
    return FretsInput(frets = frets, baseFret = baseFret)
}

/**
 * Ensures a chords line aligns in length with a lyrics line: pads with
 * trailing spaces if chords are shorter, trims trailing spaces if chords
 * are longer (but only if the extra characters are all whitespace — real
 * chord symbols past the lyrics' length are never silently dropped).
 */
fun alignChordsWithLyrics(chords: String?, lyrics: String?): String {
    val chordsStr = chords ?: ""
    val lyricsStr = lyrics ?: ""
    if (chordsStr.length < lyricsStr.length) {
        return chordsStr + " ".repeat(lyricsStr.length - chordsStr.length)
    }
    if (chordsStr.length > lyricsStr.length) {
        val extra = chordsStr.substring(lyricsStr.length)
        if (extra.isBlank()) {
            return chordsStr.substring(0, lyricsStr.length)
        }
    }
    return chordsStr
}
