package com.songnotes.core.domain

/**
 * Ported from the desktop web app's `src/utils/chords.js`
 * (`normalizeChordName`) — Phase 5 of the plan ("Domain logic port"),
 * whose Done criterion is exactly what `ChordsGoldenFixtureTest` in this
 * module's `src/test` checks: running the same chord strings through both
 * this Kotlin function and the real JS one produces byte-identical
 * output. The fixtures that test reads from (this module's `src/test/resources/spec`
 * directory) were generated by running the actual JS implementation over
 * a broad set of inputs, not hand-predicted — see the desktop `SongNotes`
 * repo's `src/test/generate-golden-fixtures.test.js`.
 *
 * This is a faithful line-by-line port, not a reimplementation from a
 * description — the ordering of the `.replace()` chain in the JS version
 * matters (e.g. the `maj#7`/`maj7` rules must run before the bare `maj`
 * rule, which would otherwise strip `maj` first and leave a meaningless
 * `#7`), so the Kotlin version preserves that exact ordering.
 *
 * [CHORD_DB_KEYS] was, for Phase 5, intentionally just the **key set** —
 * nothing in that phase's scope (chord-name normalization and transposition)
 * needed the actual fretboard shapes. Phase 8 ("Editor UI") now needs those
 * for real, so [CHORD_DB] (full `frets`/`baseFret`/`barre` per chord) and
 * [lookupChord] are ported below too, verified against `spec/chord-db.json`/
 * `spec/lookup-chord.json` by `ChordDbGoldenFixtureTest`. [CHORD_DB_KEYS]
 * stays as its own binding (equal to `CHORD_DB.keys`) since existing callers
 * ([tokenizeChordLine]) only ever needed membership, not the voicing data.
 */

private val ENHARMONIC: Map<String, String> = mapOf(
    "Gb" to "F#", "Gbm" to "F#m", "Gb7" to "F#7",
    "Cb" to "B", "Cbm" to "Bm",
    "Fb" to "E", "Fbm" to "Em",
    "A#m" to "Bbm",
    "Ebm" to "D#m",
)

/**
 * Normalize a raw user-typed chord name to a canonical key in
 * [CHORD_DB_KEYS]. Returns the normalized name (even if not a recognized
 * chord) — mirrors the JS version's contract exactly, including that the
 * root letter is uppercased unconditionally without validating it's
 * actually A–G.
 */
fun normalizeChordName(raw: String?): String {
    if (raw.isNullOrBlank()) return ""
    val s = raw.trim()

    // Root note.
    val root = s[0].uppercaseChar()
    var rest = s.substring(1)

    // Accidental right after root.
    var acc = ""
    if (rest.isNotEmpty() && rest[0] == '#') {
        acc = "#"
        rest = rest.substring(1)
    } else if (rest.isNotEmpty() && rest[0] == 'b' &&
        !Regex("^[0-9]").containsMatchIn(rest.substring(1))
    ) {
        // treat 'b' as flat only if the next char is not a digit (e.g. "Db" not "D7")
        acc = "b"
        rest = rest.substring(1)
    }

    // Normalize quality suffixes — same order as the JS .replace() chain;
    // order matters (see the maj#7/maj7-before-bare-maj comment above).
    rest = rest.replace(Regex("^-"), "m")
        .replace(Regex("^\\+"), "aug")
        .replace(Regex("^°"), "dim")
        .replace(Regex("^minor\\b", RegexOption.IGNORE_CASE), "m")
        .replace(Regex("^min\\b", RegexOption.IGNORE_CASE), "m")
        .replace(Regex("^maj\\s*#7\\b", RegexOption.IGNORE_CASE), "maj7")
        .replace(Regex("^maj\\s*7\\b", RegexOption.IGNORE_CASE), "maj7")
        .replace(Regex("^maj\\s*9\\b", RegexOption.IGNORE_CASE), "maj9")
        .replace(Regex("^maj\\b", RegexOption.IGNORE_CASE), "")
        .replace(Regex("^M\\b"), "")
        .replace(Regex("^add9\\b", RegexOption.IGNORE_CASE), "add9")
        .replace(Regex("^add11\\b", RegexOption.IGNORE_CASE), "add11")
        .replace(Regex("^sus2\\b", RegexOption.IGNORE_CASE), "sus2")
        .replace(Regex("^sus4\\b", RegexOption.IGNORE_CASE), "sus4")
        .replace(Regex("^sus\\b", RegexOption.IGNORE_CASE), "sus4")
        // strip slash bass note
        .replace(Regex("/[A-G][b#]?\\s*$"), "")
        .trim()

    val name = root + acc + rest
    return ENHARMONIC[name] ?: name
}

/** A barre position, 0-indexed string numbers (lowE=0), matching the web app's `chords.js` shape exactly. */
data class ChordBarre(val fret: Int, val fromString: Int, val toString: Int)

/**
 * One chord voicing: [frets] is `[lowE, A, D, G, B, highE]`, `-1` = muted,
 * `0` = open, `N` = absolute fret number. [baseFret] is the first fret of
 * the 4-fret display window. [barre] is only ever present on [CHORD_DB]
 * entries — never on a song's own `customChords` (the web app's UI has no
 * barre editor, only the 6-value fret-string editor [parseFretsInput]
 * parses).
 */
data class ChordVoicing(val frets: List<Int>, val baseFret: Int, val barre: ChordBarre? = null)

/**
 * Ported from the web app's `src/utils/chords.js` `CHORD_DB` — hand-transcribed
 * (it's data, not a function, so there's no "run the real implementation"
 * fixture strategy to apply the way [normalizeChordName]'s port uses), then
 * verified byte-for-byte against `spec/chord-db.json` (a literal dump of the
 * real JS object, not hand-typed) by `ChordDbGoldenFixtureTest` — so a
 * transcription slip here fails a fast JVM test instead of silently
 * shipping a wrong fretboard diagram.
 */
val CHORD_DB: Map<String, ChordVoicing> = mapOf(
    // === MAJOR ===
    "C" to ChordVoicing(listOf(-1, 3, 2, 0, 1, 0), 1),
    "D" to ChordVoicing(listOf(-1, -1, 0, 2, 3, 2), 1),
    "E" to ChordVoicing(listOf(0, 2, 2, 1, 0, 0), 1),
    "F" to ChordVoicing(listOf(1, 3, 3, 2, 1, 1), 1, ChordBarre(1, 0, 5)),
    "G" to ChordVoicing(listOf(3, 2, 0, 0, 0, 3), 1),
    "A" to ChordVoicing(listOf(-1, 0, 2, 2, 2, 0), 1),
    "B" to ChordVoicing(listOf(-1, 2, 4, 4, 4, 2), 2, ChordBarre(2, 1, 5)),
    "Bb" to ChordVoicing(listOf(-1, 1, 3, 3, 3, 1), 1, ChordBarre(1, 1, 5)),
    "Eb" to ChordVoicing(listOf(-1, -1, 1, 3, 4, 3), 1),
    "Ab" to ChordVoicing(listOf(4, 6, 6, 5, 4, 4), 4, ChordBarre(4, 0, 5)),
    "Db" to ChordVoicing(listOf(-1, 4, 6, 6, 6, 4), 4, ChordBarre(4, 1, 5)),
    "F#" to ChordVoicing(listOf(2, 4, 4, 3, 2, 2), 2, ChordBarre(2, 0, 5)),
    "Gb" to ChordVoicing(listOf(2, 4, 4, 3, 2, 2), 2, ChordBarre(2, 0, 5)),
    "C#" to ChordVoicing(listOf(-1, 4, 6, 6, 6, 4), 4, ChordBarre(4, 1, 5)),
    "G#" to ChordVoicing(listOf(4, 6, 6, 5, 4, 4), 4, ChordBarre(4, 0, 5)),
    "A#" to ChordVoicing(listOf(-1, 1, 3, 3, 3, 1), 1, ChordBarre(1, 1, 5)),
    "D#" to ChordVoicing(listOf(-1, -1, 1, 3, 4, 3), 1),
    // === MINOR ===
    "Am" to ChordVoicing(listOf(-1, 0, 2, 2, 1, 0), 1),
    "Bm" to ChordVoicing(listOf(-1, 2, 4, 4, 3, 2), 2, ChordBarre(2, 1, 5)),
    "Cm" to ChordVoicing(listOf(-1, 3, 5, 5, 4, 3), 3, ChordBarre(3, 1, 5)),
    "Dm" to ChordVoicing(listOf(-1, -1, 0, 2, 3, 1), 1),
    "Em" to ChordVoicing(listOf(0, 2, 2, 0, 0, 0), 1),
    "Fm" to ChordVoicing(listOf(1, 3, 3, 1, 1, 1), 1, ChordBarre(1, 0, 5)),
    "Gm" to ChordVoicing(listOf(3, 5, 5, 3, 3, 3), 3, ChordBarre(3, 0, 5)),
    "Bbm" to ChordVoicing(listOf(-1, 1, 3, 3, 2, 1), 1, ChordBarre(1, 1, 5)),
    "F#m" to ChordVoicing(listOf(2, 4, 4, 2, 2, 2), 2, ChordBarre(2, 0, 5)),
    "Gbm" to ChordVoicing(listOf(2, 4, 4, 2, 2, 2), 2, ChordBarre(2, 0, 5)),
    "C#m" to ChordVoicing(listOf(-1, 4, 6, 6, 5, 4), 4, ChordBarre(4, 1, 5)),
    "Dbm" to ChordVoicing(listOf(-1, 4, 6, 6, 5, 4), 4, ChordBarre(4, 1, 5)),
    "G#m" to ChordVoicing(listOf(4, 6, 6, 4, 4, 4), 4, ChordBarre(4, 0, 5)),
    "Abm" to ChordVoicing(listOf(4, 6, 6, 4, 4, 4), 4, ChordBarre(4, 0, 5)),
    "D#m" to ChordVoicing(listOf(-1, 6, 8, 8, 7, 6), 6, ChordBarre(6, 1, 5)),
    // === DOMINANT 7 ===
    "C7" to ChordVoicing(listOf(-1, 3, 2, 3, 1, 0), 1),
    "D7" to ChordVoicing(listOf(-1, -1, 0, 2, 1, 2), 1),
    "E7" to ChordVoicing(listOf(0, 2, 0, 1, 0, 0), 1),
    "F7" to ChordVoicing(listOf(1, 3, 1, 2, 1, 1), 1, ChordBarre(1, 0, 5)),
    "G7" to ChordVoicing(listOf(3, 2, 0, 0, 0, 1), 1),
    "A7" to ChordVoicing(listOf(-1, 0, 2, 0, 2, 0), 1),
    "B7" to ChordVoicing(listOf(-1, 2, 1, 2, 0, 2), 1),
    "Bb7" to ChordVoicing(listOf(-1, 1, 3, 1, 3, 1), 1, ChordBarre(1, 1, 5)),
    // === MAJOR 7 ===
    "Cmaj7" to ChordVoicing(listOf(-1, 3, 2, 0, 0, 0), 1),
    "Dmaj7" to ChordVoicing(listOf(-1, -1, 0, 2, 2, 2), 1),
    "Emaj7" to ChordVoicing(listOf(0, 2, 1, 1, 0, 0), 1),
    "Fmaj7" to ChordVoicing(listOf(-1, -1, 3, 2, 1, 0), 1),
    "Gmaj7" to ChordVoicing(listOf(3, 2, 0, 0, 0, 2), 1),
    "Amaj7" to ChordVoicing(listOf(-1, 0, 2, 1, 2, 0), 1),
    // === MINOR 7 ===
    "Am7" to ChordVoicing(listOf(-1, 0, 2, 0, 1, 0), 1),
    "Bm7" to ChordVoicing(listOf(-1, 2, 4, 2, 3, 2), 2, ChordBarre(2, 1, 5)),
    "Cm7" to ChordVoicing(listOf(-1, 3, 5, 3, 4, 3), 3, ChordBarre(3, 1, 5)),
    "Dm7" to ChordVoicing(listOf(-1, -1, 0, 2, 1, 1), 1),
    "Em7" to ChordVoicing(listOf(0, 2, 0, 0, 0, 0), 1),
    "Fm7" to ChordVoicing(listOf(1, 3, 1, 1, 1, 1), 1, ChordBarre(1, 0, 5)),
    "Gm7" to ChordVoicing(listOf(3, 5, 3, 3, 3, 3), 3, ChordBarre(3, 0, 5)),
    // === SUS ===
    "Asus2" to ChordVoicing(listOf(-1, 0, 2, 2, 0, 0), 1),
    "Asus4" to ChordVoicing(listOf(-1, 0, 2, 2, 3, 0), 1),
    "Dsus2" to ChordVoicing(listOf(-1, -1, 0, 2, 3, 0), 1),
    "Dsus4" to ChordVoicing(listOf(-1, -1, 0, 2, 3, 3), 1),
    "Esus4" to ChordVoicing(listOf(0, 2, 2, 2, 0, 0), 1),
    "Gsus4" to ChordVoicing(listOf(3, 3, 0, 0, 1, 3), 1),
    // === ADD ===
    "Cadd9" to ChordVoicing(listOf(-1, 3, 2, 0, 3, 3), 1),
    "Gadd9" to ChordVoicing(listOf(3, 2, 0, 2, 0, 3), 1),
    "Dadd9" to ChordVoicing(listOf(-1, -1, 0, 2, 3, 0), 1),
    // === DIM ===
    "Bdim" to ChordVoicing(listOf(-1, 2, 3, 4, -1, -1), 1),
    "Adim" to ChordVoicing(listOf(-1, 0, 1, 2, -1, -1), 1),
    "Edim" to ChordVoicing(listOf(0, 1, 2, 3, -1, -1), 1),
    // === SIXTH ===
    "C6" to ChordVoicing(listOf(-1, 0, 2, 2, 1, 3), 1),
    "D6" to ChordVoicing(listOf(-1, -1, 0, 2, 0, 2), 1),
    "G6" to ChordVoicing(listOf(3, 2, 0, 0, 0, 0), 1),
    "A6" to ChordVoicing(listOf(-1, 0, 2, 2, 2, 2), 1),
    // === AUGMENTED ===
    "Caug" to ChordVoicing(listOf(-1, 3, 2, 1, 1, -1), 1),
    // === DIMINISHED 7 ===
    "Cdim7" to ChordVoicing(listOf(2, -1, 1, 2, 1, -1), 1),
    // === POWER ===
    "A5" to ChordVoicing(listOf(-1, 0, 2, 2, -1, -1), 1),
    "E5" to ChordVoicing(listOf(0, 2, 2, -1, -1, -1), 1),
    "G5" to ChordVoicing(listOf(3, 5, 5, -1, -1, -1), 3),
    "D5" to ChordVoicing(listOf(-1, -1, 0, 2, 3, -1), 1),
)

/**
 * Look up a raw chord name. `customChords` (a song's own user-entered
 * voicings, keyed by normalized chord name) takes priority over [CHORD_DB],
 * so a user can override a built-in voicing they think is wrong, not just
 * fill in a gap. Ported from `lookupChord` in the web app's `chords.js`.
 */
fun lookupChord(raw: String?, customChords: Map<String, ChordVoicing>? = null): ChordVoicing? {
    val name = normalizeChordName(raw)
    if (name.isEmpty()) return null
    customChords?.get(name)?.let { return it }
    return CHORD_DB[name]
}

/** Just the recognized chord names — see this file's own doc comment for why no voicing data. */
val CHORD_DB_KEYS: Set<String> = CHORD_DB.keys

/**
 * One token of a chord-track line — ported from `tokenizeChordLine`'s
 * per-token object shape in the JS source. [chordName] is null only for
 * whitespace tokens (the JS version simply omits the key there); for
 * every other token it's always set, falling back to [text] itself if
 * [normalizeChordName] produced an empty string.
 */
data class ChordToken(
    val text: String,
    val isChord: Boolean,
    val looksLikeChord: Boolean,
    val isWhitespace: Boolean,
    val chordName: String?,
)

/**
 * Splits a chord-track string into whitespace-run and non-whitespace
 * tokens, classifying each non-whitespace token against [CHORD_DB_KEYS]
 * (plus [customChords], if given — a song's own user-entered voicings,
 * keyed by normalized chord name, taking priority the same way
 * [lookupChord]-equivalent logic would upstream; nothing calls this with
 * a non-null value yet, ported for shape-fidelity ahead of the editor
 * phase that will).
 *
 * Ported by hand-walking `\s+` matches rather than translating
 * `text.split(/(\s+)/)` literally — Kotlin's `String.split` doesn't have
 * an equivalent to JS's capturing-group split (which keeps the
 * delimiters in the result array); this achieves the same effect
 * (whitespace runs become their own tokens, interspersed with the
 * non-whitespace parts between them) without ever producing the
 * empty-string artifacts the JS version's `if (!part) continue` exists
 * to skip.
 */
fun tokenizeChordLine(text: String?, customChords: Map<String, Any?>? = null): List<ChordToken> {
    if (text.isNullOrEmpty()) return emptyList()
    val tokens = mutableListOf<ChordToken>()
    var lastEnd = 0
    for (match in Regex("\\s+").findAll(text)) {
        if (match.range.first > lastEnd) {
            tokens.add(nonWhitespaceChordToken(text.substring(lastEnd, match.range.first), customChords))
        }
        tokens.add(ChordToken(text = match.value, isChord = false, looksLikeChord = false, isWhitespace = true, chordName = null))
        lastEnd = match.range.last + 1
    }
    if (lastEnd < text.length) {
        tokens.add(nonWhitespaceChordToken(text.substring(lastEnd), customChords))
    }
    return tokens
}

private fun nonWhitespaceChordToken(part: String, customChords: Map<String, Any?>?): ChordToken {
    val chordName = normalizeChordName(part)
    val inDb = chordName in CHORD_DB_KEYS || (customChords?.get(chordName) != null)
    return ChordToken(
        text = part,
        isChord = inDb,
        looksLikeChord = Regex("^[A-G][#b]?").containsMatchIn(part),
        isWhitespace = false,
        chordName = chordName.ifEmpty { part },
    )
}

/**
 * Formats a frets array (as stored on a chord voicing) into the compact
 * space-separated text a user can edit, e.g. `[-1,3,2,0,1,0]` -> `"x 3 2 0 1 0"`.
 */
fun formatFretsForInput(frets: List<Int>): String = frets.joinToString(" ") { if (it == -1) "x" else it.toString() }

/** Parsed result of [parseFretsInput] — mirrors the JS version's `{frets, baseFret}` shape. */
data class FretsInput(val frets: List<Int>, val baseFret: Int)

/**
 * Parses a user-typed "x 3 2 0 1 0"-style string (low-E to high-E, 'x' for
 * muted) into a voicing, or null if it isn't exactly 6 valid values.
 * `baseFret` is derived automatically: 1 if the whole shape fits in the
 * first 4 frets (the common case), otherwise the lowest fretted position —
 * same convention every hand-written `CHORD_DB` entry in the JS source
 * follows.
 *
 * One deliberate divergence from a strict byte-for-byte port:
 * `p.toIntOrNull() ?: return null` instead of a direct `p.toInt()` — JS's
 * `Number(p)` never throws (an absurdly long digit string just becomes a
 * huge-but-valid number, which the following `n > 24` check then rejects
 * anyway), but Kotlin's `String.toInt()` throws `NumberFormatException` on
 * overflow. Both end up returning null for that input either way, so this
 * doesn't change behavior — it just reaches the same "reject" outcome
 * without a crash risk Kotlin's typed parsing would otherwise introduce
 * that the JS source never had.
 */
fun parseFretsInput(raw: String?): FretsInput? {
    if (raw.isNullOrEmpty()) return null
    val parts = raw.trim().split(Regex("\\s+"))
    if (parts.size != 6) return null
    val frets = mutableListOf<Int>()
    for (p in parts) {
        if (Regex("^x$", RegexOption.IGNORE_CASE).matches(p)) {
            frets.add(-1)
            continue
        }
        if (!Regex("^\\d+$").matches(p)) return null
        val n = p.toIntOrNull() ?: return null
        if (n > 24) return null
        frets.add(n)
    }
    val played = frets.filter { it > 0 }
    val baseFret = if (played.isEmpty() || played.max() <= 4) 1 else played.min()
    return FretsInput(frets = frets, baseFret = baseFret)
}

/**
 * Ensures a chords line aligns in length with a lyrics line: pads with
 * trailing spaces if chords are shorter, trims trailing spaces if chords
 * are longer (but only if the extra characters are all whitespace — real
 * chord symbols past the lyrics' length are never silently dropped).
 */
fun alignChordsWithLyrics(chords: String?, lyrics: String?): String {
    val chordsStr = chords ?: ""
    val lyricsStr = lyrics ?: ""
    if (chordsStr.length < lyricsStr.length) {
        return chordsStr + " ".repeat(lyricsStr.length - chordsStr.length)
    }
    if (chordsStr.length > lyricsStr.length) {
        val extra = chordsStr.substring(lyricsStr.length)
        if (extra.isBlank()) {
            return chordsStr.substring(0, lyricsStr.length)
        }
    }
    return chordsStr
}
