package com.songnotes.core.domain

/**
 * Ported from the desktop web app's `src/utils/chords.js`
 * (`normalizeChordName`) — Phase 5 of the plan ("Domain logic port"),
 * whose Done criterion is exactly what `ChordsGoldenFixtureTest` in this
 * module's `src/test` checks: running the same chord strings through both
 * this Kotlin function and the real JS one produces byte-identical
 * output. The fixtures that test reads from (this module's `src/test/resources/spec`
 * directory) were generated by running the actual JS implementation over
 * a broad set of inputs, not hand-predicted — see the desktop `SongNotes`
 * repo's `src/test/generate-golden-fixtures.test.js`.
 *
 * This is a faithful line-by-line port, not a reimplementation from a
 * description — the ordering of the `.replace()` chain in the JS version
 * matters (e.g. the `maj#7`/`maj7` rules must run before the bare `maj`
 * rule, which would otherwise strip `maj` first and leave a meaningless
 * `#7`), so the Kotlin version preserves that exact ordering.
 *
 * [CHORD_DB_KEYS] is intentionally just the **key set** ported here, not
 * the full voicing/fret data (`frets`/`baseFret`/`barre`) — nothing in
 * this phase's scope (chord-name normalization and transposition) needs
 * the actual fretboard shapes; those belong to chord-diagram rendering,
 * which is Phase 8 ("Editor UI") territory.
 */

private val ENHARMONIC: Map<String, String> = mapOf(
    "Gb" to "F#", "Gbm" to "F#m", "Gb7" to "F#7",
    "Cb" to "B", "Cbm" to "Bm",
    "Fb" to "E", "Fbm" to "Em",
    "A#m" to "Bbm",
    "Ebm" to "D#m",
)

/**
 * Normalize a raw user-typed chord name to a canonical key in
 * [CHORD_DB_KEYS]. Returns the normalized name (even if not a recognized
 * chord) — mirrors the JS version's contract exactly, including that the
 * root letter is uppercased unconditionally without validating it's
 * actually A–G.
 */
fun normalizeChordName(raw: String?): String {
    if (raw.isNullOrBlank()) return ""
    val s = raw.trim()

    // Root note.
    val root = s[0].uppercaseChar()
    var rest = s.substring(1)

    // Accidental right after root.
    var acc = ""
    if (rest.isNotEmpty() && rest[0] == '#') {
        acc = "#"
        rest = rest.substring(1)
    } else if (rest.isNotEmpty() && rest[0] == 'b' &&
        !Regex("^[0-9]").containsMatchIn(rest.substring(1))
    ) {
        // treat 'b' as flat only if the next char is not a digit (e.g. "Db" not "D7")
        acc = "b"
        rest = rest.substring(1)
    }

    // Normalize quality suffixes — same order as the JS .replace() chain;
    // order matters (see the maj#7/maj7-before-bare-maj comment above).
    rest = rest.replace(Regex("^-"), "m")
        .replace(Regex("^\\+"), "aug")
        .replace(Regex("^°"), "dim")
        .replace(Regex("^minor\\b", RegexOption.IGNORE_CASE), "m")
        .replace(Regex("^min\\b", RegexOption.IGNORE_CASE), "m")
        .replace(Regex("^maj\\s*#7\\b", RegexOption.IGNORE_CASE), "maj7")
        .replace(Regex("^maj\\s*7\\b", RegexOption.IGNORE_CASE), "maj7")
        .replace(Regex("^maj\\s*9\\b", RegexOption.IGNORE_CASE), "maj9")
        .replace(Regex("^maj\\b", RegexOption.IGNORE_CASE), "")
        .replace(Regex("^M\\b"), "")
        .replace(Regex("^add9\\b", RegexOption.IGNORE_CASE), "add9")
        .replace(Regex("^add11\\b", RegexOption.IGNORE_CASE), "add11")
        .replace(Regex("^sus2\\b", RegexOption.IGNORE_CASE), "sus2")
        .replace(Regex("^sus4\\b", RegexOption.IGNORE_CASE), "sus4")
        .replace(Regex("^sus\\b", RegexOption.IGNORE_CASE), "sus4")
        // strip slash bass note
        .replace(Regex("/[A-G][b#]?\\s*$"), "")
        .trim()

    val name = root + acc + rest
    return ENHARMONIC[name] ?: name
}

/** Just the recognized chord names — see this file's own doc comment for why no voicing data. */
val CHORD_DB_KEYS: Set<String> = setOf(
    "C", "D", "E", "F", "G", "A", "B", "Bb", "Eb", "Ab", "Db", "F#", "Gb", "C#", "G#", "A#", "D#",
    "Am", "Bm", "Cm", "Dm", "Em", "Fm", "Gm", "Bbm", "F#m", "Gbm", "C#m", "Dbm", "G#m", "Abm", "D#m",
    "C7", "D7", "E7", "F7", "G7", "A7", "B7", "Bb7",
    "Cmaj7", "Dmaj7", "Emaj7", "Fmaj7", "Gmaj7", "Amaj7",
    "Am7", "Bm7", "Cm7", "Dm7", "Em7", "Fm7", "Gm7",
    "Asus2", "Asus4", "Dsus2", "Dsus4", "Esus4", "Gsus4",
    "Cadd9", "Gadd9", "Dadd9",
    "Bdim", "Adim", "Edim",
    "C6", "D6", "G6", "A6",
    "Caug", "Cdim7",
    "A5", "E5", "G5", "D5",
)
