package com.songnotes.core.domain

import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Phase 5's actual Done criterion: chord strings run through both the
 * real JS `normalizeChordName` and this Kotlin port produce byte-identical
 * output. The fixtures here were generated by running the real JS
 * implementation (not hand-predicted) — see the desktop `SongNotes`
 * repo's `src/test/generate-golden-fixtures.test.js` — so a failure here
 * means this Kotlin port actually disagrees with the JS source of truth,
 * not that the fixture's expectation might itself be wrong.
 */
class ChordsGoldenFixtureTest {

    @Suppress("UNCHECKED_CAST")
    private fun loadFixtures(resourceName: String): List<Map<String, Any?>> {
        val text = requireNotNull(javaClass.getResourceAsStream(resourceName)) {
            "Missing test resource $resourceName"
        }.bufferedReader(Charsets.UTF_8).readText()
        return MinimalJson.parse(text) as List<Map<String, Any?>>
    }

    @Test
    fun `normalizeChordName matches the JS fixtures exactly`() {
        val fixtures = loadFixtures("/spec/normalize-chord-name.json")
        assertEquals("expected a substantial fixture set", true, fixtures.size > 1000)

        var failures = 0
        val failureExamples = StringBuilder()
        for (fixture in fixtures) {
            val input = fixture["input"] as String
            val expected = fixture["output"] as String
            val actual = normalizeChordName(input)
            if (actual != expected) {
                failures++
                if (failures <= 20) {
                    failureExamples.appendLine("  input=${input.repr()} expected=${expected.repr()} actual=${actual.repr()}")
                }
            }
        }
        assertEquals(
            "normalizeChordName disagreed with the JS fixtures on $failures/${fixtures.size} cases:\n$failureExamples",
            0,
            failures,
        )
    }

    private fun String.repr(): String = "\"" + this.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
}
