package com.songnotes.core.domain

/**
 * Minimal recursive-descent JSON parser — just enough to read this
 * module's test fixture files (the `spec` directory's JSON files,
 * generated by the desktop repo's `src/test/generate-golden-fixtures.test.js`).
 * Not a general-purpose JSON library: no streaming, no custom deserialization, no
 * dependency pulled in for it — `:core:domain` stays a genuinely
 * zero-dependency pure-Kotlin module, matching its own design goal, the
 * same "hand-write it, it's small" call this codebase already made for
 * the WAV encoder in `:core:audio` rather than adding a library for one
 * file format.
 *
 * Returns `Map<String, Any?>` / `List<Any?>` / `String` / `Double` /
 * `Boolean` / `null` — callers cast to what they know the fixture shape is.
 */
object MinimalJson {
    fun parse(text: String): Any? {
        val parser = Parser(text)
        val value = parser.parseValue()
        parser.skipWhitespace()
        require(parser.pos >= text.length) { "Unexpected trailing content at offset ${parser.pos}" }
        return value
    }

    private class Parser(val text: String) {
        var pos = 0

        fun skipWhitespace() {
            while (pos < text.length && text[pos].isWhitespace()) pos++
        }

        fun parseValue(): Any? {
            skipWhitespace()
            return when (text[pos]) {
                '{' -> parseObject()
                '[' -> parseArray()
                '"' -> parseString()
                't' -> { expect("true"); true }
                'f' -> { expect("false"); false }
                'n' -> { expect("null"); null }
                else -> parseNumber()
            }
        }

        fun expect(literal: String) {
            require(text.regionMatches(pos, literal, 0, literal.length)) { "Expected '$literal' at offset $pos" }
            pos += literal.length
        }

        fun parseObject(): Map<String, Any?> {
            pos++ // consume '{'
            val map = LinkedHashMap<String, Any?>()
            skipWhitespace()
            if (text[pos] == '}') {
                pos++
                return map
            }
            while (true) {
                skipWhitespace()
                val key = parseString()
                skipWhitespace()
                require(text[pos] == ':') { "Expected ':' at offset $pos" }
                pos++
                map[key] = parseValue()
                skipWhitespace()
                when (text[pos]) {
                    ',' -> pos++
                    '}' -> { pos++; break }
                    else -> error("Expected ',' or '}' at offset $pos")
                }
            }
            return map
        }

        fun parseArray(): List<Any?> {
            pos++ // consume '['
            val list = mutableListOf<Any?>()
            skipWhitespace()
            if (text[pos] == ']') {
                pos++
                return list
            }
            while (true) {
                list.add(parseValue())
                skipWhitespace()
                when (text[pos]) {
                    ',' -> pos++
                    ']' -> { pos++; break }
                    else -> error("Expected ',' or ']' at offset $pos")
                }
            }
            return list
        }

        fun parseString(): String {
            require(text[pos] == '"') { "Expected '\"' at offset $pos" }
            pos++
            val sb = StringBuilder()
            while (text[pos] != '"') {
                val c = text[pos]
                if (c == '\\') {
                    pos++
                    when (val esc = text[pos]) {
                        '"' -> sb.append('"')
                        '\\' -> sb.append('\\')
                        '/' -> sb.append('/')
                        'b' -> sb.append('\b')
                        'f' -> sb.append('\u000C')
                        'n' -> sb.append('\n')
                        'r' -> sb.append('\r')
                        't' -> sb.append('\t')
                        'u' -> {
                            val hex = text.substring(pos + 1, pos + 5)
                            sb.append(hex.toInt(16).toChar())
                            pos += 4
                        }
                        else -> error("Unknown escape sequence '\\$esc' at offset $pos")
                    }
                    pos++
                } else {
                    sb.append(c)
                    pos++
                }
            }
            pos++ // consume closing quote
            return sb.toString()
        }

        fun parseNumber(): Double {
            val start = pos
            if (text[pos] == '-') pos++
            while (pos < text.length &&
                (text[pos].isDigit() || text[pos] == '.' || text[pos] == 'e' || text[pos] == 'E' ||
                    text[pos] == '+' || text[pos] == '-')
            ) {
                pos++
            }
            return text.substring(start, pos).toDouble()
        }
    }
}
